# Book settings
title: scverse x GSCN Workshop 2025
author: scverse community & outreach team
copyright: "2025, scverse"
logo: "../misc/ressources/scverse_logo.png"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/scverse/202504_workshop_GSCN
  branch: main
  path_to_book: notebooks

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false
  extra_navbar: ""
  extra_footer: ""
  home_page_in_navbar: true
  baseurl: "/202504_workshop_GSCN" 